---
title: Copa Tecnologia - Bizz
timezone: America/Sao_Paulo
description: Área restrita.
baseurl: "/bizz"
url: http://copatecnologia.com.br
markdown: kramdown
sass:
  style: compressed
exclude:
- node_modules
- desktop.ini
- gulpfile.js
- npm-debug.log
- package.json
